# Generated by Django 6.0.4 on 2026-05-04 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('faixa_salarial', models.CharField(choices=[('1', 'Até 1000'), ('2', '1000-2000'), ('3', '2000-3000'), ('4', 'Acima de 3000')], max_length=1)),
                ('requisitos', models.TextField()),
                ('escolaridade_minima', models.CharField(choices=[('fundamental', 'Fundamental'), ('medio', 'Médio'), ('tecnologo', 'Tecnólogo'), ('superior', 'Superior'), ('pos', 'Pós/MBA/Mestrado'), ('doutorado', 'Doutorado')], max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
