# Generated by Django 6.0.4 on 2026-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='status',
            field=models.CharField(
                choices=[('aberta', 'Aberta'), ('encerrada', 'Encerrada'), ('preenchida', 'Preenchida')],
                default='aberta',
                max_length=15,
            ),
        ),
    ]
