# Generated by Django 6.0.4 on 2026-05-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcandidato',
            name='escolaridade',
            field=models.CharField(
                choices=[
                    ('fundamental', 'Ensino fundamental'),
                    ('medio', 'Ensino médio'),
                    ('tecnologo', 'Tecnólogo'),
                    ('superior', 'Ensino Superior'),
                    ('pos', 'Pós / MBA / Mestrado'),
                    ('doutorado', 'Doutorado'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='perfilcandidato',
            name='experiencia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('principais_responsabilidades', models.TextField()),
                ('emprego_atual', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                (
                    'perfil',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='experiencias',
                        to='accounts.perfilcandidato',
                    ),
                ),
            ],
        ),
    ]
